/**
 * Dükkân paneli metin tablosu (G9 B; kaynak: SP/takim/t1/g9-dukkan-metin-son.md, A1 anahtarları birebir). Yer tutucu adları ASCII'dir
 * (`{sure}`, `{ad}` = dükkân adı, `{kucuk}`, `{tur}`); değerleri çağıran doldurur: para `para()`/`paraMili()`/`paraIsaretli()` çıktısıdır (şablonda ayrıca ₺ yazılmaz),
 * "/sa" birimi bitişik. Büyük harf yalnız cümle başında (testle korunur). Ret kodu (DUK-xx/MRK-xx) eşlemesi `DUKKAN_RET_ANAHTARI`dadır.
 */
export const DUKKAN_METIN = {
  "defter.ust.atla": "Atla",
  "defter.ust.atla_etiket": "Sıradaki adımı atla",
  "defter.ust.baslik": "Sıradaki adım",
  "dukkan.D0.oneri_baslik": "İlk dükkânın için malzemen hazır",
  "dukkan.D0.oneri_dugme": "Dükkân kur",
  "dukkan.D0.oneri_govde": "Başlangıç malzemen ilk dükkânı kurmaya yetiyor. İstersen bir hücre ve tür seçip kurabilirsin.",
  "dukkan.D0.oneri_isaret_etiket": "İşletmem, yeni öneri var",
  "dukkan.D0.oneri_kapat": "Öneriyi kapat",
  "dukkan.D0.oneri_not": "Başlangıç gıdanı rafın için sakla.",
  "dukkan.D1.baslik": "Dükkânlarım",
  "dukkan.D1.defter_kart": "Kendi tezgâhın: bir dükkân kur ve oradan ilk satışını yap.",
  "dukkan.D1.isletmem_bos": "Henüz dükkânın yok. Yapı kur → Dükkân",
  "dukkan.D1.kapali": "Bu dünyada dükkân henüz açık değil.",
  "dukkan.D1.palet_alt": "Gıda, ekmek ve benzeri malı ilçenin hane halkına sat. Raf, fiyat ve marka sende.",
  "dukkan.D1.palet_baslik": "Dükkân",
  "dukkan.D1.satir_acik": "{ad} · net ≈ {net}/sa",
  "dukkan.D1.satir_git": "Git",
  "dukkan.D1.satir_insaat": "İnşa sürüyor · {kalan}",
  "dukkan.D2.baslik": "Hangi dükkânı kuruyorsun?",
  "dukkan.D2.boy_acilmadi": "Bu dükkân boyu henüz açılmadı.",
  "dukkan.D2.boy_uyumsuz": "Bu dükkân türü bu boyda kurulamaz.",
  "dukkan.D2.hucre_sayisi": "Dükkân {n} hücre kaplar.",
  "dukkan.D2.il_sayac": "Bu ilde dükkânın: {n} / 6",
  "dukkan.D2.il_siniri": "Bu ilde en çok {n} dükkânın olabilir.",
  "dukkan.D2.ilce_sayac": "Bu ilçede dükkânın: {n} / 2",
  "dukkan.D2.ilce_siniri": "Bu ilçede en çok {n} dükkânın olabilir.",
  "dukkan.D2.tur_bakkal": "Bakkal · gündelik mallar",
  "dukkan.D2.tur_firin": "Fırın · ekmek ve gıda",
  "dukkan.D2.tur_gerekli": "Dükkân türünü seçmelisin.",
  "dukkan.D2.tur_sarkuteri": "Şarküteri · süt ürünleri",
  "dukkan.D2.tur_sayi": "bu ilçede {n} / {m}",
  "dukkan.D2.tur_sekerci": "Şekerci · tatlı",
  "dukkan.D2.tur_uyum.var": "depondaki malla satabilirsin",
  "dukkan.D2.tur_uyum.yok": "malın yok",
  "dukkan.D2.tur_uyum.yok_ithal": "malın yok; Pazar'dan alabilirsin",
  "dukkan.D2.tur_yalniz_kurarken": "Dükkân türü yalnız dükkân kurarken seçilir.",
  "dukkan.D2.tur_yapi_market": "Yapı market · cam, pencere, çelik",
  "dukkan.D2.tur_yok": "Bu dükkân türü yok.",
  "dukkan.D2.yer_ipucu": "Dükkân 1 hücre kaplar. Sahip olduğun boş bir hücreyi seç.",
  "dukkan.D3.baslik": "{tur} · 1 hücre",
  "dukkan.D3.dugme_kur": "Dükkânı kur",
  "dukkan.D3.dugme_pazar": "Pazar'dan al",
  "dukkan.D3.dugme_vazgec": "Vazgeç",
  "dukkan.D3.hazine_ret": "Hazinede yeterli para yok (gereken {n}).",
  "dukkan.D3.hazine_yetmiyor": "Hazinen bu bedeli karşılamıyor (gereken {n}, hazine {m}).",
  "dukkan.D3.indirim_notu": "İlk {n} yapında {yuzde} indirim var.",
  "dukkan.D3.insaat_siniri": "Aynı anda en çok {n} inşaat sürebilir; birinin bitmesini bekle.",
  "dukkan.D3.iptal_hatirlatma": "Pencere geldi. Emri iptal etmezsen pencere almaya devam eder.",
  "dukkan.D3.pencere_bekleme": "Pencere kısa sürede gelir.",
  "dukkan.D3.pencere_yeter": "{n} pencere gerekiyor; depondaki pencere yetiyor.",
  "dukkan.D3.pencere_yok": "Pencere {n}: stokta {var}. Pazar'dan alabilirsin (yaklaşık {tutar}).",
  "dukkan.D3.satir_arsa": "Arsa · kendi arsan: {arsa}",
  "dukkan.D3.satir_celik": "Çelik · {n}",
  "dukkan.D3.satir_dukkan": "Dükkân · {n}",
  "dukkan.D3.satir_hazine": "Hazine",
  "dukkan.D3.satir_parca": "Makine parçası · {n}",
  "dukkan.D3.satir_pencere": "Pencere · {n}",
  "dukkan.D3.satir_sure": "Süre · {n} saat",
  "dukkan.D3.satir_toplam": "Toplam",
  "dukkan.D3.stok_yetmiyor": "{mal} yetmiyor: {var} / {gereken}. Pazar'dan alabilir ya da üretebilirsin.",
  "dukkan.D3.yatirim_baslik": "Yatırım tahmini",
  "dukkan.D3.yatirim_genel": "Dükkân kendini yaklaşık {sure} içinde öder.",
  "dukkan.D3.yatirim_kirsal": "Bu ilçede küçük bir pazar var; dükkân kendini yaklaşık {n} günde öder.",
  "dukkan.D4.dikkat_stoksuz": "Dükkân hazır olunca rafına koyacak bir mal gerekecek.",
  "dukkan.D4.dugme_iptal": "İptal et (iade {yuzde})",
  "dukkan.D4.dugme_rafa_git": "Rafa git",
  "dukkan.D4.etiket": "Dükkân · iskele · {kalan}",
  "dukkan.D4.geri_alma": "Geri alma: {sure}",
  "dukkan.D4.hazir": "Dükkânın hazır.",
  "dukkan.D4.iptal_onay": "İnşaatı iptal edersen ödediğin paranın ve malzemenin {yuzde} kadarı geri gelir. İptal edilsin mi?",
  "dukkan.D4.raf_oneri": "Rafına mal koy: boş rafta satış olmaz.",
  "dukkan.D4.sen_yokken": "{yapi} bitti",
  "dukkan.D5.baslik": "Raf",
  "dukkan.D5.bilgi": "Bir mal yalnız bir yuvada olabilir. Kasa saatte en çok {n} birim satar. Mal koyunca fiyat normale döner.",
  "dukkan.D5.bos_raf_uyari": "Rafın boş: bir yuvaya mal koyunca satış başlar.",
  "dukkan.D5.bos_yuva": "Boş: mal koy",
  "dukkan.D5.degisim_cok_sik": "Fiyatı en erken {n} saat sonra değiştirebilirsin.",
  "dukkan.D5.dugme_bosalt": "Yuvayı boşalt",
  "dukkan.D5.mal_baska_rafta": "Bu mal zaten başka yuvada.",
  "dukkan.D5.mal_bilinmiyor": "Bilinmeyen mal.",
  "dukkan.D5.mal_satilamaz": "Bu dükkânda bu mal satılamaz.",
  "dukkan.D5.mal_satiri": "{mal} · stokta {n} · {fiyat}",
  "dukkan.D5.neden_kampanya_bitti": "Kampanya bitti; fiyat normale döndü.",
  "dukkan.D5.neden_karsilanmiyor": "Stoğun talebi karşılamıyor; satış düşüyor.",
  "dukkan.D5.neden_kasa_dolu": "Kasa dolu: satış kasa sınırında.",
  "dukkan.D5.neden_stoksuz": "{mal}: stoğun yok; stok gelince satış başlar",
  "dukkan.D5.raf_zaten_bos": "Raf zaten boş.",
  "dukkan.D5.raf_zaten_dolu": "Bu raf zaten bu malla dolu.",
  "dukkan.D5.secici_baslik": "Bu yuvaya hangi malı koyacaksın?",
  "dukkan.D5.secici_bos": "Bu dükkânda koyabileceğin başka mal kalmadı.",
  "dukkan.D5.secici_stoksuz": "Rafa koyacak malın yok. Bu dükkânın sattığı bir malı üret ya da Pazar'dan al.",
  "dukkan.D5.secici_stoksuz_yapi": "Yapı kur",
  "dukkan.D5.stoksuz_mal": "stoğun yok; stok gelince satış başlar",
  "dukkan.D5.tahmini_satis": "≈ {n} birim/sa",
  "dukkan.D5.yukleniyor": "Rafın yükleniyor.",
  "dukkan.D5.yuva_bekleme": "değişim: {sure} sonra",
  "dukkan.D5.yuva_gecersiz": "Geçersiz raf yuvası.",
  "dukkan.D5.yuva_kampanya_bitti": "kampanya bitti",
  "dukkan.D5.yuva_satiri": "{mal} · {kademe} · {fiyat}",
  "dukkan.D5.yuva_stoksuz": "stoğun yok",
  "dukkan.D6.bekleme_kisa": "Fiyatı en erken {m} dk sonra değiştirebilirsin.",
  "dukkan.D6.bekleme_sayac": "Fiyatı en erken {n} saat {m} dk sonra değiştirebilirsin.",
  "dukkan.D6.birim_fiyat": "{fiyat} · ≈ {n} birim/sa · net ≈ {net}/sa",
  "dukkan.D6.degisim_cok_sik": "Fiyatı en erken {n} saat sonra değiştirebilirsin.",
  "dukkan.D6.fiyat_ayni": "Fiyat zaten bu seviyede.",
  "dukkan.D6.fiyat_gecersiz": "Geçersiz fiyat.",
  "dukkan.D6.hak_bitti_gun": "Bugün kampanya hakkın bitti.",
  "dukkan.D6.hak_bitti_hafta": "Bu hafta kampanya günlerin bitti.",
  "dukkan.D6.ipucu_esnaf_payi": "Her ilçede talebin en az {esnaf_payi} kadarı ilçenin kendi esnafına gider; kalanı dükkânlar paylaşır.",
  "dukkan.D6.ipucu_kademe": "Üst kademede satış biraz azalır, birim başına gelirin artar.",
  "dukkan.D6.ipucu_kasa_dolu": "Kasan doluyken kademe değişse de satışın çoğu zaman aynı kalır.",
  "dukkan.D6.ipucu_normal": "Normal fiyat, çoğu zaman en iyi dengedir.",
  "dukkan.D6.kademe_kampanya": "Kampanya",
  "dukkan.D6.kademe_normal": "Normal",
  "dukkan.D6.kademe_uygun": "Uygun",
  "dukkan.D6.kademe_yuksek": "Yüksek",
  "dukkan.D6.kampanya_bitti": "Kampanya bitti; fiyat normale döndü.",
  "dukkan.D6.kampanya_dugme": "Kampanya başlat",
  "dukkan.D6.kampanya_gun": "Bugün en çok {n} saat kampanya yapabilirsin.",
  "dukkan.D6.kampanya_hafta": "Bu hafta en çok {n} gün kampanya yapabilirsin.",
  "dukkan.D6.kampanya_hak": "Bugün en çok {n} saat; en geç gün sonunda biter. Bu hafta {m} gün hakkın var.",
  "dukkan.D6.kampanya_kapali": "Kampanya fiyatı şu an kullanılamıyor.",
  "dukkan.D6.kampanya_suruyor": "Kampanya sürüyor: {n} saat {m} dk kaldı",
  "dukkan.D6.kampanya_uyari": "Kampanya fiyatı dünya pazarında satmaktan düşüktür; satış artmayabilir.",
  "dukkan.D6.once_mal": "Önce rafa mal koy.",
  "dukkan.D6.yuksek_uyari": "Fiyat yükselince satışın düşebilir; kasa doluysa gelir artar.",
  "dukkan.D7.aciklama": "Marka yalnızca tabeladır; satışı ya da fiyatı etkilemez.",
  "dukkan.D7.ad_yasakli": "Bu ad kullanılamaz; başka bir ad dene.",
  "dukkan.D7.ad_yazilmali": "Marka adı yazılmalı.",
  "dukkan.D7.alan": "Marka adı",
  "dukkan.D7.baslik": "Marka",
  "dukkan.D7.bosluk_art_arda": "Art arda boşluk olamaz.",
  "dukkan.D7.bosluk_kenar": "Marka adı boşlukla başlayıp bitemez.",
  "dukkan.D7.buyuk_harf_notu": "Büyük harf yazabilirsin; ad küçük harfle kaydedilir.",
  "dukkan.D7.cift_tirnak_tire": "Çift tırnak ya da uzun tire yerine düz kesme işareti (') ve tire (-) kullan.",
  "dukkan.D7.dugme_kaydet": "Kaydet",
  "dukkan.D7.dukkan_zaten_markada": "Dükkân zaten bu markada.",
  "dukkan.D7.harf_gerekli": "Marka adında en az bir harf olmalı.",
  "dukkan.D7.karakter": "Marka adında yalnız harf, rakam, boşluk, nokta, kesme işareti, tire ve & kullanılabilir.",
  "dukkan.D7.kvkk_uyari": "Marka adın dünyadaki herkese görünür ve kalıcıdır. Kişisel bilgi yazma.",
  "dukkan.D7.marka_siniri": "En çok {n} marka tanımlayabilirsin.",
  "dukkan.D7.marka_yok": "Geçersiz marka. · Önce marka tanımlamalısın.",
  "dukkan.D7.markasiz": "markasız",
  "dukkan.D7.onizleme": "Tabelada böyle görünür: {kucuk}",
  "dukkan.D7.renk_ad.cam": "çam",
  "dukkan.D7.renk_ad.eflatun": "eflatun",
  "dukkan.D7.renk_ad.fistik": "fıstık",
  "dukkan.D7.renk_ad.gok": "gök",
  "dukkan.D7.renk_ad.gul-kurusu": "gül kurusu",
  "dukkan.D7.renk_ad.hardal": "hardal",
  "dukkan.D7.renk_ad.kestane": "kestane",
  "dukkan.D7.renk_ad.kobalt": "kobalt",
  "dukkan.D7.renk_ad.nar-cicegi": "nar çiçeği",
  "dukkan.D7.renk_ad.patlican": "patlıcan",
  "dukkan.D7.renk_ad.zeytin": "zeytin",
  "dukkan.D7.renk_ad.zumrut": "zümrüt",
  "dukkan.D7.renk_grup": "Renk",
  "dukkan.D7.renk_oge": "Renk: {ad}",
  "dukkan.D7.simge_ad.bird": "kuş",
  "dukkan.D7.simge_ad.feather": "tüy",
  "dukkan.D7.simge_ad.flame": "alev",
  "dukkan.D7.simge_ad.flower": "çiçek",
  "dukkan.D7.simge_ad.gem": "mücevher",
  "dukkan.D7.simge_ad.leaf": "yaprak",
  "dukkan.D7.simge_ad.mountain": "dağ",
  "dukkan.D7.simge_ad.sun": "güneş",
  "dukkan.D7.simge_grup": "Simge",
  "dukkan.D7.simge_oge": "Simge: {ad}",
  "dukkan.D7.simge_renk": "Geçersiz simge. · Geçersiz renk.",
  "dukkan.D7.uzunluk": "Marka adı 2 ile 24 karakter arasında olmalı.",
  "dukkan.D7.yer_tutucu": "adsiz marka",
  "dukkan.D7.zaten_boyle": "Marka zaten böyle.",
  "dukkan.D8.dikkat_kampanya": "Kampanya bitti",
  "dukkan.D8.dikkat_kasa": "Kasa dolu: fiyatı yükseltmeyi düşünebilirsin",
  "dukkan.D8.dikkat_mal_var": "Rafına koyabileceğin başka mal var",
  "dukkan.D8.dikkat_stok": "{mal} stoğun bitti; yuvada satılmıyor",
  "dukkan.D8.ilk_satis": "Dükkânında ilk satış oldu; hayırlı olsun.",
  "dukkan.D8.kart_gelir": "Gelir ≈ {gelir}/sa",
  "dukkan.D8.kart_gider": "Gider {g}/sa",
  "dukkan.D8.kart_net": "Net ≈ {net}/sa",
  "dukkan.D8.kart_satis": "Tahmini satış ≈ {n} birim/sa",
  "dukkan.D8.kasa": "Kasa %{n} dolu: satış kasa sınırında",
  "dukkan.D8.ozet_satiri": "{ad} · net ≈ {net}/sa",
  "dukkan.D8.satis_yok": "Henüz satış yok.",
  "dukkan.D8.sen_yokken": "Dükkânından gelir: {tutar}.",
  "dukkan.D8.toplam_satis": "Dükkânlardan toplam gelir: {n}/sa",
  "dukkan.D8.yukleniyor": "Dükkânın bilgisi yükleniyor.",
  "dukkan.D81.dugme": "Dükkânı kaldır",
  "dukkan.D81.dugme_onay": "Dükkânı kaldır",
  "dukkan.D81.henuz_bitmedi": "Dükkân henüz bitmedi; inşaatı iptal edebilirsin.",
  "dukkan.D81.menu": "Daha fazla",
  "dukkan.D81.onay": "Dükkânı kaldırırsan harcadığın para ve malzeme geri gelmez. Arsan, depondaki mallar ve markan sende kalır. Yeniden kurarsan bedeli yeniden ödersin. Kaldırılsın mı?",
  "dukkan.D81.sonuc": "Dükkân kaldırıldı. Arsan ve malların sende.",
  "dukkan.D81.yok": "Bu dükkân yok.",
} as const;

export type DukkanMetinAnahtari = keyof typeof DUKKAN_METIN;

/** Ret kodu → metin anahtarı (tablonun `kod` sütunu; birden çok koda bağlı satır ilk koduyla yazılır). */
export const DUKKAN_RET_ANAHTARI: Readonly<Record<string, DukkanMetinAnahtari>> = {
  "DUK-00": "dukkan.D1.kapali",
  "DUK-01": "dukkan.D2.tur_gerekli",
  "DUK-02": "dukkan.D2.tur_yalniz_kurarken",
  "DUK-03": "dukkan.D2.tur_yok",
  "DUK-04": "dukkan.D2.boy_acilmadi",
  "DUK-05": "dukkan.D2.boy_uyumsuz",
  "DUK-06": "dukkan.D2.ilce_siniri",
  "DUK-07": "dukkan.D2.il_siniri",
  "DUK-08": "dukkan.D2.hucre_sayisi",
  "DUK-10": "dukkan.D81.yok",
  "DUK-12": "dukkan.D5.yuva_gecersiz",
  "DUK-13": "dukkan.D5.mal_satilamaz",
  "DUK-14": "dukkan.D5.mal_baska_rafta",
  "DUK-15": "dukkan.D5.mal_bilinmiyor",
  "DUK-16": "dukkan.D6.fiyat_gecersiz",
  "DUK-17": "dukkan.D6.once_mal",
  "DUK-18": "dukkan.D5.degisim_cok_sik",
  "DUK-20": "dukkan.D6.kampanya_kapali",
  "DUK-21": "dukkan.D6.kampanya_hafta",
  "DUK-22": "dukkan.D6.kampanya_gun",
  "DUK-23": "dukkan.D81.henuz_bitmedi",
  "MRK-01": "dukkan.D7.marka_yok",
  "MRK-02": "dukkan.D7.marka_siniri",
  "MRK-03": "dukkan.D7.ad_yazilmali",
  "MRK-04": "dukkan.D7.uzunluk",
  "MRK-05": "dukkan.D7.karakter",
  "MRK-06": "dukkan.D7.bosluk_kenar",
  "MRK-07": "dukkan.D7.bosluk_art_arda",
  "MRK-08": "dukkan.D7.harf_gerekli",
  "MRK-09": "dukkan.D7.simge_renk",
  "MRK-10": "dukkan.D7.simge_renk",
  "MRK-11": "dukkan.D7.zaten_boyle",
  "MRK-12": "dukkan.D7.ad_yasakli",
  "MRK-13": "dukkan.D7.marka_yok",
  "MRK-14": "dukkan.D7.dukkan_zaten_markada",
};

const YER_TUTUCU = /\{([a-z_]+)\}/g;

/** `{ad}` yer tutucularını doldurur (HTML kaçışı çağıranındır; verilmeyen yer tutucu olduğu gibi kalır). */
export function dukkanMetni(anahtar: DukkanMetinAnahtari, yer: Readonly<Record<string, string | number>> = {}): string {
  return DUKKAN_METIN[anahtar].replace(YER_TUTUCU, (tum, ad: string) => (ad in yer ? String(yer[ad]) : tum));
}
